# Generated by Django 4.1.2 on 2022-10-11 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ferramentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('geometria', models.CharField(max_length=100)),
                ('raio', models.IntegerField()),
                ('vida_util', models.IntegerField()),
                ('data_cadastro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
